version: '3'

services:
  selenium:
    image: selenium/standalone-chrome
    ports:
     - 4444:4444
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./start.sh"]
    depends_on:
      - selenuim
